' ******************************************************************************
' swxJRNL.swj - journal recorded on 06/19/25 by a_golubev
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "ТЕНШ.467883.002.13.001 Основание", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03710343760667118157, -0.07330382858376201238
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.003331992208352818705

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0

' Named View
Part.ShowNamedView2 "*Справа", 4
Part.ViewZoomtofit2
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 55
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ActivateDoc2 "ТЕНШ.467883.002.13.001 Основание 2", False, longstatus
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.001766830362222437207, -0.01999195325011690963
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01999195325011690963
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.009995976625058454815
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003533660724444874415, -0.01999195325011690963
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01413464289777949766, -0.04997988312529227928
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02120196434666924562, -0.04664789091693945927
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01766830362222437251, -0.07330382858376201238
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0123678125355570611, -0.01665996104176409309
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01060098217333462281, -0.02998792987517536618
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005300491086667311405, -0.01665996104176409309
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.001766830362222437207, -0.009995976625058454815
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007067321448889748829, -0.03331992208352818619
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.001766830362222437207, -0.01665996104176409309
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003533660724444874415, -0.009995976625058454815
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003533660724444874415, -0.009995976625058454815
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.001766830362222437207, -0.01665996104176409309
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007067321448889748829, -0.02665593766682254964
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0123678125355570611, -0.03331992208352818619
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.001766830362222437207, -0.01665996104176409309
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007067321448889748829, -0.03665191429188100619
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003533660724444874415, -0.04997988312529227928
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003533660724444874415, -0.01999195325011690963
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.001766830362222437207, -0.01332796883341127482
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01999195325011690963
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003533660724444874415, -0.06997183637540919932
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.03331992208352818619
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.005300491086667311405, -0.05997585975035073236
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.04664789091693945927
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.07663582079211482545
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.05331187533364509928
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.05664386754199791235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.1132877350839958247
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.06663984416705637237
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.06663984416705637237
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.1232837117090542778
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0899637896255260916
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003533660724444874415, -0.03665191429188100619
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.04997988312529227928
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.006663984416705637411
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.003331992208352818705
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.001766830362222437207, -0.02332394545846972964
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.001766830362222437207, -0.006663984416705637411
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.009995976625058454815
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.006663984416705637411
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.009995976625058454815
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003533660724444874415, -0.02332394545846972964
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.03331992208352818619
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.009995976625058454815
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01665996104176409309
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.03665191429188100619
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.009995976625058454815
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01665996104176409309
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.04331589870858663927
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02998792987517536618
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.003331992208352818705
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.003331992208352818705

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0

' Named View
Part.ShowNamedView2 "*Справа", 4
Part.ViewZoomtofit2
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 3
myModelView.FrameTop = 58
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowNormal
swApp.ActivateDoc2 "ТЕНШ.467883.002.13.001 Основание", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 1867
myModelView.FrameTop = 58
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowNormal
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03599205986109427907, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02879364788887541632, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01439682394443770816, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01799602993054713954, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01439682394443770816, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0323928538749848477, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02159523591665656744, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01439682394443770816, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.06118650176386026401, 0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01439682394443770816, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01439682394443770816, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, -0.003603137396252638087

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
swApp.ActivateDoc2 "ТЕНШ.467883.002.13.001 Основание 2", False, longstatus
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.06478570774996969539, 0.02522196177376847051
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.2627420369859881921, 0.05765019834004220939
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02161882437751582939
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, -0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, -0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02879364788887541632, 0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01439682394443770816, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, 0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01439682394443770816, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01439682394443770816, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, -0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01439682394443770816, -0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01799602993054713954, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01439682394443770816, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007206274792505276174

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
swApp.ActivateDoc2 "ТЕНШ.467883.002.13.001 Основание", False, longstatus
Set Part = swApp.ActiveDoc
boolstatus = Part.Extension.SelectByID2("Вырез-Вытянуть5", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Вырез-Вытянуть6", "BODYFEATURE", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Вырез-Вытянуть5", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Вырез-Вытянуть5", "BODYFEATURE", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Вырез-Вытянуть6", "BODYFEATURE", 0, 0, 0, True, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("Вырез-Вытянуть6", "BODYFEATURE", 0, 0, 0, False, 0, Nothing, 0)
swApp.ActivateDoc2 "ТЕНШ.467883.002.13.001 Основание 2", False, longstatus
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.1331706214860488013, 0.1080941218875791504
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01799602993054713954, 0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01799602993054713954, 0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01439682394443770816, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, -0.02161882437751582939
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01439682394443770816, -0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, -0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, -0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01799602993054713954, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01799602993054713954, 0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, 0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, 0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01439682394443770816, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02159523591665656744, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02879364788887541632, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02159523591665656744, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02519444190276599188, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02159523591665656744, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01799602993054713954, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02879364788887541632, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01799602993054713954, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01799602993054713954, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02159523591665656744, -0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, -0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02519444190276599188, -0.02882509917002110469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, -0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, -0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, -0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01439682394443770816, -0.02161882437751582939
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02519444190276599188, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02159523591665656744, -0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03959126584720370351, -0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01799602993054713954, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03599205986109427907, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02159523591665656744, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01799602993054713954, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01799602993054713954, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01799602993054713954, 0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01439682394443770816, 0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01439682394443770816, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01799602993054713954, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02159523591665656744, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02879364788887541632, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01439682394443770816, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01439682394443770816, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01439682394443770816, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01799602993054713954, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01799602993054713954, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01799602993054713954, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01799602993054713954, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01439682394443770816, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01799602993054713954, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02159523591665656744, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, 0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, 0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.003603137396252638087

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.1547658574027054035, 0.03603137396252638347, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02519444190276599188, 0.007206274792505276174, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03959126584720370351, 0.007206274792505276174, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02879364788887541632, 0.007206274792505276174, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03959126584720370351, 0.007206274792505276174, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03599205986109427907, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.05038888380553198376, 0.007206274792505276174, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03599205986109427907, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03959126584720370351, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03599205986109427907, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03599205986109427907, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02879364788887541632, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02519444190276599188, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01079761795832828372, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02879364788887541632, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01079761795832828372, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01079761795832828372, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02879364788887541632, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01079761795832828372, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01079761795832828372, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03599205986109427907, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02159523591665656744, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02519444190276599188, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03599205986109427907, -0.003603137396252638087, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02159523591665656744, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03599205986109427907, -0.01441254958501055235, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03959126584720370351, -0.007206274792505276174, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0323928538749848477, -0.02522196177376847051, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02879364788887541632, -0.01441254958501055235, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03599205986109427907, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01439682394443770816, -0.003603137396252638087, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04319047183331313489, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0323928538749848477, -0.01801568698126319173, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01079761795832828372, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03599205986109427907, -0.01441254958501055235, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01439682394443770816, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01079761795832828372, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02519444190276599188, -0.007206274792505276174, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.00719841197221885408, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01079761795832828372, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.00359920598610942704, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.00719841197221885408, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01079761795832828372, -0.003603137396252638087, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01079761795832828372, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01079761795832828372, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01079761795832828372, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02159523591665656744, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.00359920598610942704, 0, 0.06340000000000145519, 0.02108202726618912948, -0.04804434964488280002

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00719841197221885408, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00359920598610942704, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00359920598610942704, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01439682394443770816, 0.007206274792505276174, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00359920598610942704, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00359920598610942704, 0.003603137396252638087, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01439682394443770816, 0.007206274792505276174, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00359920598610942704, 0.003603137396252638087, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01079761795832828372, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00359920598610942704, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00719841197221885408, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00359920598610942704, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00719841197221885408, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01799602993054713954, 0.01080941218875791469, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00359920598610942704, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00719841197221885408, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01079761795832828372, 0.007206274792505276174, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00359920598610942704, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00359920598610942704, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01799602993054713954, 0.01080941218875791469, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01439682394443770816, 0.007206274792505276174, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00359920598610942704, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01079761795832828372, 0.007206274792505276174, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00719841197221885408, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02519444190276599188, 0.003603137396252638087, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00359920598610942704, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01079761795832828372, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01079761795832828372, 0.007206274792505276174, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02879364788887541632, 0.007206274792505276174, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01799602993054713954, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.05758729577775083264, 0.007206274792505276174, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04678967781942255932, 0.01441254958501055235, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02519444190276599188, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04678967781942255932, 0.007206274792505276174, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02159523591665656744, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02519444190276599188, 0.007206274792505276174, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03959126584720370351, 0.007206274792505276174, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01439682394443770816, 0.007206274792505276174, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01799602993054713954, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03959126584720370351, 0.01441254958501055235, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02519444190276599188, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02879364788887541632, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01799602993054713954, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03599205986109427907, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02519444190276599188, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03599205986109427907, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03959126584720370351, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02519444190276599188, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02879364788887541632, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02519444190276599188, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02519444190276599188, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03599205986109427907, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03959126584720370351, 0.007206274792505276174, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01439682394443770816, 0.007206274792505276174, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01079761795832828372, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01079761795832828372, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02879364788887541632, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01079761795832828372, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01079761795832828372, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01799602993054713954, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02879364788887541632, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01799602993054713954, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04678967781942255932, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01799602993054713954, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02879364788887541632, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02519444190276599188, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01799602993054713954, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03599205986109427907, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02879364788887541632, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01799602993054713954, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02879364788887541632, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02519444190276599188, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02159523591665656744, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04319047183331313489, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03959126584720370351, -0.01080941218875791469, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02879364788887541632, -0.007206274792505276174, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03959126584720370351, -0.007206274792505276174, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01799602993054713954, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.04678967781942255932, -0.01080941218875791469, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.06478570774996969539, -0.007206274792505276174, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.07198411972218855814, -0.01801568698126319173, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0755833257082979687, -0.01801568698126319173, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0755833257082979687, -0.02161882437751582939, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.06118650176386026401, -0.007206274792505276174, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.06118650176386026401, -0.01080941218875791469, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.05038888380553198376, -0.007206274792505276174, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03959126584720370351, -0.007206274792505276174, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03959126584720370351, -0.007206274792505276174, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00359920598610942704, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01799602993054713954, -0.007206274792505276174, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.00719841197221885408, 0, 0.06349999999994793143, 0.02841475478601296345, -0.04660643892036375746

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0323928538749848477, -0.02522196177376847051
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01799602993054713954, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, -0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03599205986109427907, -0.02161882437751582939
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02879364788887541632, -0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.05398808979164141514, -0.02882509917002110469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01799602993054713954, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03959126584720370351, -0.03242823656627374235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0323928538749848477, -0.03242823656627374235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02159523591665656744, -0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03959126584720370351, -0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.05398808979164141514, -0.03603137396252638347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04319047183331313489, -0.04323764875503165878
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04319047183331313489, -0.03603137396252638347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01799602993054713954, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01439682394443770816, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02159523591665656744, -0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02159523591665656744, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02159523591665656744, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01799602993054713954, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02159523591665656744, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01799602993054713954, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02879364788887541632, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03599205986109427907, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02159523591665656744, 0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0323928538749848477, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02159523591665656744, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01799602993054713954, 0.02161882437751582939
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0323928538749848477, 0.02161882437751582939
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02519444190276599188, 0.03242823656627374235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01439682394443770816, 0.03963451135877901765
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02519444190276599188, 0.03242823656627374235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0323928538749848477, 0.04323764875503165878
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0.02161882437751582939
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01439682394443770816, 0.02882509917002110469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01439682394443770816, 0.02882509917002110469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01799602993054713954, 0.03963451135877901765
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02159523591665656744, 0.03242823656627374235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0.02882509917002110469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0.02522196177376847051
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02882509917002110469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02879364788887541632, 0.03963451135877901765
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01439682394443770816, 0.03242823656627374235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01439682394443770816, 0.02161882437751582939
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, 0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0323928538749848477, 0.02161882437751582939
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, 0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01439682394443770816, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02879364788887541632, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, 0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0323928538749848477, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03599205986109427907, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02879364788887541632, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04319047183331313489, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01439682394443770816, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03599205986109427907, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03599205986109427907, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04678967781942255932, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03959126584720370351, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02879364788887541632, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03599205986109427907, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02159523591665656744, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02879364788887541632, -0.02522196177376847051
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01439682394443770816, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02159523591665656744, -0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, -0.02161882437751582939
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02159523591665656744, -0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01439682394443770816, -0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, -0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, -0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, -0.03603137396252638347
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01439682394443770816, -0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, -0.02882509917002110469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, -0.0468407861512842999
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, -0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01439682394443770816, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, -0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, -0.02522196177376847051
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, -0.02161882437751582939
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01439682394443770816, -0.02161882437751582939
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02519444190276599188, -0.03963451135877901765
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01439682394443770816, -0.02882509917002110469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, -0.02161882437751582939
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01439682394443770816, -0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01799602993054713954, -0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02159523591665656744, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02519444190276599188, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01439682394443770816, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02519444190276599188, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02159523591665656744, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01799602993054713954, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02159523591665656744, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02879364788887541632, 0.02522196177376847051
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01439682394443770816, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02879364788887541632, 0.02882509917002110469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01439682394443770816, 0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02159523591665656744, 0.02161882437751582939
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01079761795832828372, 0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02159523591665656744, 0.02161882437751582939
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01439682394443770816, 0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01439682394443770816, 0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, 0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00359920598610942704, 0.02161882437751582939
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, 0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.00719841197221885408, 0.02882509917002110469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.05044392354753694102
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01439682394443770816, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.02882509917002110469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0468407861512842999
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02879364788887541632, 0.03963451135877901765
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01439682394443770816, 0.02882509917002110469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0323928538749848477, 0.02522196177376847051
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01439682394443770816, 0.02882509917002110469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01439682394443770816, 0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, 0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02159523591665656744, 0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02159523591665656744, 0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02519444190276599188, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03599205986109427907, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02879364788887541632, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02159523591665656744, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03599205986109427907, -0.01801568698126319173
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0323928538749848477, -0.02882509917002110469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01799602993054713954, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02879364788887541632, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.03959126584720370351, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01799602993054713954, -0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02159523591665656744, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01799602993054713954, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02879364788887541632, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.04678967781942255932, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01439682394443770816, -0.01441254958501055235
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01799602993054713954, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01079761795832828372, -0.007206274792505276174
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00359920598610942704, -0.003603137396252638087
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.00719841197221885408, -0.01080941218875791469
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.007206274792505276174

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0

' Close Document
swPart = Nothing
Set Part = Nothing
swApp.CloseDoc "ТЕНШ.467883.002.13.001 Основание 2"
swApp.ActivateDoc2 "ТЕНШ.467883.002.13.001 Основание", False, longstatus
Set Part = swApp.ActiveDoc
Part.ClearSelection2 True
swApp.ExitApp
End Sub
